In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('../data/bakery.csv')
df

,data-product-id,data-product-name,data-product-type,data-product-on-offer,data-product-index,image-url,product-page,product-name,product-size,item-price,price-per-unit,offer-description,category
0,872615,Mr Kipling Viennese Whirls,G,True,246,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling Viennese Whirls,6s,£1.98,33p each,25% Off. Was £2.65,Bakery
1,56312,Mr Kipling French Fancies,G,True,161,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling French Fancies,8s,£2.36,29.5p each,25% Off. Was £3.15,Bakery
2,684311,Mr Kipling 8 Angel Slices,G,True,277,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling 8 Angel Slices,8s,£2.96,37p each,25% Off. Was £3.95,Bakery
3,540706,Waitrose 4 Brioche Burger Buns,G,True,4,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/waitros...,Waitrose 4 Brioche Burger Buns,4s,£1.31,32.8p each,25% Off. Was £1.75,Bakery
4,783454,Hovis Seed Sensations Multiseeded Sliced Bread,G,False,5,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-s...,Hovis Seed Sensations Multiseeded Sliced Bread,800g,£1.90,23.8p/100g,NaN,Bakery
...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,384230,Galaxy Chocolate Cake Bars,G,False,481,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/galaxy-...,Galaxy Chocolate Cake Bars,5s,£2.25,45p each,NaN,Bakery
481,376437,25cm Football Cake,E,False,482,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/25cm-fo...,25cm Football Cake,each,£30.00,£30 each,NaN,Bakery
482,374515,Waitrose Ready To Bake 4 All Butter Cinnamon S...,G,True,483,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/waitros...,Waitrose Ready To Bake 4 All Butter Cinnamon S...,360g,£2.60,£7.23/kg,Introductory Offer.Will be £3.30,Bakery
483,297903,Dr. Oetker Old School Cake Mix Vanilla,G,False,484,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/dr-oetk...,Dr. Oetker Old School Cake Mix Vanilla,436g,£3.00,£6.89/kg,NaN,Bakery
484,77133,Cohens Bakery Buckingham Rye Bread,G,False,485,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/cohens-...,Cohens Bakery Buckingham Rye Bread,400g,£2.10,52.5p/100g,NaN,Bakery

In [5]:
selected_columns = ['data-product-id','data-product-name','data-product-type']
print(df[selected_columns])

     data-product-id                                  data-product-name  \
0             872615                         Mr Kipling Viennese Whirls
1              56312                          Mr Kipling French Fancies
2             684311                          Mr Kipling 8 Angel Slices
3             540706                     Waitrose 4 Brioche Burger Buns
4             783454     Hovis Seed Sensations Multiseeded Sliced Bread
..               ...                                                ...
480           384230                         Galaxy Chocolate Cake Bars
481           376437                                 25cm Football Cake
482           374515  Waitrose Ready To Bake 4 All Butter Cinnamon S...
483           297903             Dr. Oetker Old School Cake Mix Vanilla
484            77133                 Cohens Bakery Buckingham Rye Bread

    data-product-type
0                   G
1                   G
2                   G
3                   G
4                   G
..                ...
480                 G
481                 E
482                 G
483                 G
484                 G

[485 rows x 3 columns]

In [4]:
if df['product-name'].equals (df['data-product-name']):
    print(" The columns are identical ")
    df = df.drop(columns=['data-product-name'])

else:
    print("The columns are not identical. Dropping the Columns")

 The columns are identical

In [6]:
df = df.rename(columns= {
                'data-product-id':'product-id',
                'data-product-name':'pro_name',
                'data-product-type':'pro_type',
                'data-product-on-offer':'offer',
                'data-product-index':'index',
                'image-url':'url',
                'product-page':'page',
                'product-name':'name',
                'product-size':'size',
                'item-price':'price',
                'price-per-unit':'unit',
                'offer-description':'offer_desc',
                'category':'catgs'}
                )
df

,product-id,pro_name,pro_type,offer,index,url,page,name,size,price,unit,offer_desc,catgs
0,872615,Mr Kipling Viennese Whirls,G,True,246,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling Viennese Whirls,6s,£1.98,33p each,25% Off. Was £2.65,Bakery
1,56312,Mr Kipling French Fancies,G,True,161,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling French Fancies,8s,£2.36,29.5p each,25% Off. Was £3.15,Bakery
2,684311,Mr Kipling 8 Angel Slices,G,True,277,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling 8 Angel Slices,8s,£2.96,37p each,25% Off. Was £3.95,Bakery
3,540706,Waitrose 4 Brioche Burger Buns,G,True,4,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/waitros...,Waitrose 4 Brioche Burger Buns,4s,£1.31,32.8p each,25% Off. Was £1.75,Bakery
4,783454,Hovis Seed Sensations Multiseeded Sliced Bread,G,False,5,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-s...,Hovis Seed Sensations Multiseeded Sliced Bread,800g,£1.90,23.8p/100g,NaN,Bakery
...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,384230,Galaxy Chocolate Cake Bars,G,False,481,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/galaxy-...,Galaxy Chocolate Cake Bars,5s,£2.25,45p each,NaN,Bakery
481,376437,25cm Football Cake,E,False,482,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/25cm-fo...,25cm Football Cake,each,£30.00,£30 each,NaN,Bakery
482,374515,Waitrose Ready To Bake 4 All Butter Cinnamon S...,G,True,483,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/waitros...,Waitrose Ready To Bake 4 All Butter Cinnamon S...,360g,£2.60,£7.23/kg,Introductory Offer.Will be £3.30,Bakery
483,297903,Dr. Oetker Old School Cake Mix Vanilla,G,False,484,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/dr-oetk...,Dr. Oetker Old School Cake Mix Vanilla,436g,£3.00,£6.89/kg,NaN,Bakery
484,77133,Cohens Bakery Buckingham Rye Bread,G,False,485,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/cohens-...,Cohens Bakery Buckingham Rye Bread,400g,£2.10,52.5p/100g,NaN,Bakery

In [ ]:
item_price_list =df['price'].tolist()

new_list = []

for element in item_price_list:
    if '£' in element:
        new_element = element.replace('£', '')
    elif 'p' in element:
        new_element = element.replace('p','')
        new_element = '0.' + new_element
    else:
        new_element = element

    new_list.append(new_element)

df['price'] = new_list
df['price'] = df['price'].astype(float)

In [ ]:
new_list

In [ ]:
df.info()

In [6]:
df[["price"]]

      price
0     £1.98
1     £2.36
2     £2.96
3     £1.31
4     £1.90
..      ...
480   £2.25
481  £30.00
482   £2.60
483   £3.00
484   £2.10

[485 rows x 1 columns]

In [7]:
df.loc[df['price'].str.contains('p'), 'price'] = df['price'].apply(lambda x: '0.'+str.replace(x,'p',''))

In [8]:
df[['price']]

      price
0     £1.98
1     £2.36
2     £2.96
3     £1.31
4     £1.90
..      ...
480   £2.25
481  £30.00
482   £2.60
483   £3.00
484   £2.10

[485 rows x 1 columns]

In [9]:
df.loc[df['price'].str.contains('£'), 'price'] = df['price'].str.replace('£','')

In [10]:
df[["price"]]

     price
0     1.98
1     2.36
2     2.96
3     1.31
4     1.90
..     ...
480   2.25
481  30.00
482   2.60
483   3.00
484   2.10

[485 rows x 1 columns]

In [18]:
df['price'] = df['price'].astype(float)
df[["price"]]

     price
0     1.98
1     2.36
2     2.96
3     1.31
4     1.90
..     ...
480   2.25
481  30.00
482   2.60
483   3.00
484   2.10

[485 rows x 1 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 485 entries, 0 to 484
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product-id  485 non-null    int64
 1   pro_name    485 non-null    object
 2   pro_type    485 non-null    object
 3   offer       485 non-null    bool
 4   index       485 non-null    int64
 5   url         485 non-null    object
 6   page        485 non-null    object
 7   name        485 non-null    object
 8   size        482 non-null    object
 9   price       485 non-null    object
 10  unit        463 non-null    object
 11  offer_desc  52 non-null     object
 12  catgs       485 non-null    object
dtypes: bool(1), int64(2), object(10)
memory usage: 46.1+ KB

In [12]:
df.shape

(485, 13)

In [13]:
df.drop_duplicates()

,product-id,pro_name,pro_type,offer,index,url,page,name,size,price,unit,offer_desc,catgs
0,872615,Mr Kipling Viennese Whirls,G,True,246,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling Viennese Whirls,6s,1.98,33p each,25% Off. Was £2.65,Bakery
1,56312,Mr Kipling French Fancies,G,True,161,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling French Fancies,8s,2.36,29.5p each,25% Off. Was £3.15,Bakery
2,684311,Mr Kipling 8 Angel Slices,G,True,277,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/mr-kipl...,Mr Kipling 8 Angel Slices,8s,2.96,37p each,25% Off. Was £3.95,Bakery
3,540706,Waitrose 4 Brioche Burger Buns,G,True,4,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/waitros...,Waitrose 4 Brioche Burger Buns,4s,1.31,32.8p each,25% Off. Was £1.75,Bakery
4,783454,Hovis Seed Sensations Multiseeded Sliced Bread,G,False,5,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/hovis-s...,Hovis Seed Sensations Multiseeded Sliced Bread,800g,1.90,23.8p/100g,NaN,Bakery
...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,384230,Galaxy Chocolate Cake Bars,G,False,481,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/galaxy-...,Galaxy Chocolate Cake Bars,5s,2.25,45p each,NaN,Bakery
481,376437,25cm Football Cake,E,False,482,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/25cm-fo...,25cm Football Cake,each,30.00,£30 each,NaN,Bakery
482,374515,Waitrose Ready To Bake 4 All Butter Cinnamon S...,G,True,483,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/waitros...,Waitrose Ready To Bake 4 All Butter Cinnamon S...,360g,2.60,£7.23/kg,Introductory Offer.Will be £3.30,Bakery
483,297903,Dr. Oetker Old School Cake Mix Vanilla,G,False,484,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/dr-oetk...,Dr. Oetker Old School Cake Mix Vanilla,436g,3.00,£6.89/kg,NaN,Bakery
484,77133,Cohens Bakery Buckingham Rye Bread,G,False,485,https://ecom-su-static-prod.wtrecom.com/images...,https://www.waitrose.com/ecom/products/cohens-...,Cohens Bakery Buckingham Rye Bread,400g,2.10,52.5p/100g,NaN,Bakery